/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { PetstoreError } from "./petstore-error.js";

/**
 * Not Found error
 */
export type ApiErrorInvalidInputData = {
  status: number;
  error: string;
};

/**
 * Not Found error
 */
export class ApiErrorInvalidInput extends PetstoreError {
  status: number;
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorInvalidInputData;

  constructor(
    err: ApiErrorInvalidInputData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.error = err.error;

    this.name = "ApiErrorInvalidInput";
  }
}

/** @internal */
export const ApiErrorInvalidInput$inboundSchema: z.ZodMiniType<
  ApiErrorInvalidInput,
  unknown
> = z.pipe(
  z.object({
    status: types.number(),
    error: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ApiErrorInvalidInput(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
