export type PlanName = 'basic' | 'pro' | 'elite'

export type FeatureKey =
  | 'portfolioDashboard'
  | 'propertyLimit'
  | 'dealAnalysis'
  | 'dealAnalysisLimit'
  | 'dealPipeline'
  | 'dealPipelineLimit'
  | 'tenantManagement'
  | 'tenantLimit'
  | 'basicDocuments'
  | 'mobileAccess'
  | 'heatMap'
  | 'tenantScreening'
  | 'aiAssistant'
  | 'aiMessagesLimit'
  | 'marketIntelligence'
  | 'liveMarketData'
  | 'timeAnalysis'
  | 'accounting'
  | 'financingHub'
  | 'contractorNetwork'
  | 'fullDocumentVault'
  | 'emailAgents'
  | 'voiceAgents'
  | 'smsAgents'
  | 'autopilotMode'
  | 'syndicationTools'
  | 'unlimitedProperties'
  | 'unlimitedDeals'
  | 'unlimitedAI'
  | 'prioritySupport'
  | 'dedicatedManager'
  | 'whiteLabel'
  | 'zoneIntelligence'
  | 'insuranceAutomation'
  | 'exitStrategyPlanner'
  | 'bulkPortfolioImport'
  | 'aiDealRecommendation'
  | 'liveRentAutofill'
  | 'portfolioBenchmarking'

interface Plan {
  name: string
  price: number
  popular?: boolean
  features: Record<FeatureKey, boolean | number>
}

export const PLANS: Record<PlanName, Plan> = {
  basic: {
    name: 'Basic',
    price: 20,
    features: {
      portfolioDashboard: true,
      propertyLimit: 3,
      dealAnalysis: true,
      dealAnalysisLimit: 5,
      dealPipeline: true,
      dealPipelineLimit: 10,
      tenantManagement: true,
      tenantLimit: 10,
      basicDocuments: true,
      mobileAccess: true,
      heatMap: false,
      tenantScreening: false,
      aiAssistant: false,
      aiMessagesLimit: 0,
      marketIntelligence: false,
      liveMarketData: false,
      timeAnalysis: false,
      accounting: false,
      financingHub: false,
      contractorNetwork: false,
      fullDocumentVault: false,
      emailAgents: false,
      voiceAgents: false,
      smsAgents: false,
      autopilotMode: false,
      syndicationTools: false,
      unlimitedProperties: false,
      unlimitedDeals: false,
      unlimitedAI: false,
      prioritySupport: false,
      dedicatedManager: false,
      whiteLabel: false,
      zoneIntelligence: false,
      insuranceAutomation: false,
      exitStrategyPlanner: false,
      bulkPortfolioImport: false,
      aiDealRecommendation: false,
      liveRentAutofill: false,
      portfolioBenchmarking: false,
    },
  },
  pro: {
    name: 'Pro',
    price: 99,
    popular: true,
    features: {
      portfolioDashboard: true,
      propertyLimit: 20,
      dealAnalysis: true,
      dealAnalysisLimit: 50,
      dealPipeline: true,
      dealPipelineLimit: 100,
      tenantManagement: true,
      tenantLimit: 100,
      basicDocuments: true,
      mobileAccess: true,
      heatMap: true,
      tenantScreening: true,
      aiAssistant: true,
      aiMessagesLimit: 200,
      marketIntelligence: true,
      liveMarketData: true,
      timeAnalysis: true,
      accounting: true,
      financingHub: true,
      contractorNetwork: true,
      fullDocumentVault: true,
      emailAgents: false,
      voiceAgents: false,
      smsAgents: false,
      autopilotMode: false,
      syndicationTools: false,
      unlimitedProperties: false,
      unlimitedDeals: false,
      unlimitedAI: false,
      prioritySupport: false,
      dedicatedManager: false,
      whiteLabel: false,
      zoneIntelligence: true,
      insuranceAutomation: true,
      exitStrategyPlanner: true,
      bulkPortfolioImport: true,
      aiDealRecommendation: true,
      liveRentAutofill: true,
      portfolioBenchmarking: true,
    },
  },
  elite: {
    name: 'Elite',
    price: 199,
    features: {
      portfolioDashboard: true,
      propertyLimit: Infinity,
      dealAnalysis: true,
      dealAnalysisLimit: Infinity,
      dealPipeline: true,
      dealPipelineLimit: Infinity,
      tenantManagement: true,
      tenantLimit: Infinity,
      basicDocuments: true,
      mobileAccess: true,
      heatMap: true,
      tenantScreening: true,
      aiAssistant: true,
      aiMessagesLimit: Infinity,
      marketIntelligence: true,
      liveMarketData: true,
      timeAnalysis: true,
      accounting: true,
      financingHub: true,
      contractorNetwork: true,
      fullDocumentVault: true,
      emailAgents: true,
      voiceAgents: true,
      smsAgents: true,
      autopilotMode: true,
      syndicationTools: true,
      unlimitedProperties: true,
      unlimitedDeals: true,
      unlimitedAI: true,
      prioritySupport: true,
      dedicatedManager: true,
      whiteLabel: true,
      zoneIntelligence: true,
      insuranceAutomation: true,
      exitStrategyPlanner: true,
      bulkPortfolioImport: true,
      aiDealRecommendation: true,
      liveRentAutofill: true,
      portfolioBenchmarking: true,
    },
  },
}
