/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApiResponse = {
  code?: number | undefined;
  type?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const ApiResponse$inboundSchema: z.ZodMiniType<ApiResponse, unknown> = z
  .object({
    code: types.optional(types.number()),
    type: types.optional(types.string()),
    message: types.optional(types.string()),
  });

export function apiResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApiResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiResponse' from JSON`,
  );
}
