/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Category = {
  id?: number | undefined;
  name?: string | undefined;
};

/** @internal */
export const Category$inboundSchema: z.ZodMiniType<Category, unknown> = z
  .object({
    id: types.optional(types.number()),
    name: types.optional(types.string()),
  });
/** @internal */
export type Category$Outbound = {
  id?: number | undefined;
  name?: string | undefined;
};

/** @internal */
export const Category$outboundSchema: z.ZodMiniType<
  Category$Outbound,
  Category
> = z.object({
  id: z.optional(z.int()),
  name: z.optional(z.string()),
});

export function categoryToJSON(category: Category): string {
  return JSON.stringify(Category$outboundSchema.parse(category));
}
export function categoryFromJSON(
  jsonString: string,
): SafeParseResult<Category, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Category$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Category' from JSON`,
  );
}
