/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Order Status
 */
export const OrderStatus = {
  Placed: "placed",
  Approved: "approved",
  Delivered: "delivered",
} as const;
/**
 * Order Status
 */
export type OrderStatus = OpenEnum<typeof OrderStatus>;

export type Order = {
  id?: number | undefined;
  petId?: number | undefined;
  quantity?: number | undefined;
  shipDate?: Date | undefined;
  /**
   * Order Status
   */
  status?: OrderStatus | undefined;
  complete?: boolean | undefined;
};

/** @internal */
export const OrderStatus$inboundSchema: z.ZodMiniType<OrderStatus, unknown> =
  openEnums.inboundSchema(OrderStatus);
/** @internal */
export const OrderStatus$outboundSchema: z.ZodMiniType<string, OrderStatus> =
  openEnums.outboundSchema(OrderStatus);

/** @internal */
export const Order$inboundSchema: z.ZodMiniType<Order, unknown> = z.object({
  id: types.optional(types.number()),
  petId: types.optional(types.number()),
  quantity: types.optional(types.number()),
  shipDate: types.optional(types.date()),
  status: types.optional(OrderStatus$inboundSchema),
  complete: types.optional(types.boolean()),
});
/** @internal */
export type Order$Outbound = {
  id?: number | undefined;
  petId?: number | undefined;
  quantity?: number | undefined;
  shipDate?: string | undefined;
  status?: string | undefined;
  complete?: boolean | undefined;
};

/** @internal */
export const Order$outboundSchema: z.ZodMiniType<Order$Outbound, Order> = z
  .object({
    id: z.optional(z.int()),
    petId: z.optional(z.int()),
    quantity: z.optional(z.int()),
    shipDate: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    status: z.optional(OrderStatus$outboundSchema),
    complete: z.optional(z.boolean()),
  });

export function orderToJSON(order: Order): string {
  return JSON.stringify(Order$outboundSchema.parse(order));
}
export function orderFromJSON(
  jsonString: string,
): SafeParseResult<Order, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Order$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Order' from JSON`,
  );
}
