/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  Category,
  Category$inboundSchema,
  Category$Outbound,
  Category$outboundSchema,
} from "./category.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  Tag,
  Tag$inboundSchema,
  Tag$Outbound,
  Tag$outboundSchema,
} from "./tag.js";

/**
 * pet status in the store
 */
export const PetStatus = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * pet status in the store
 */
export type PetStatus = OpenEnum<typeof PetStatus>;

export type Pet = {
  id?: number | undefined;
  name: string;
  category?: Category | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag> | undefined;
  /**
   * pet status in the store
   */
  status?: PetStatus | undefined;
};

/** @internal */
export const PetStatus$inboundSchema: z.ZodMiniType<PetStatus, unknown> =
  openEnums.inboundSchema(PetStatus);
/** @internal */
export const PetStatus$outboundSchema: z.ZodMiniType<string, PetStatus> =
  openEnums.outboundSchema(PetStatus);

/** @internal */
export const Pet$inboundSchema: z.ZodMiniType<Pet, unknown> = z.object({
  id: types.optional(types.number()),
  name: types.string(),
  category: types.optional(Category$inboundSchema),
  photoUrls: z.array(types.string()),
  tags: types.optional(z.array(Tag$inboundSchema)),
  status: types.optional(PetStatus$inboundSchema),
});
/** @internal */
export type Pet$Outbound = {
  id?: number | undefined;
  name: string;
  category?: Category$Outbound | undefined;
  photoUrls: Array<string>;
  tags?: Array<Tag$Outbound> | undefined;
  status?: string | undefined;
};

/** @internal */
export const Pet$outboundSchema: z.ZodMiniType<Pet$Outbound, Pet> = z.object({
  id: z.optional(z.int()),
  name: z.string(),
  category: z.optional(Category$outboundSchema),
  photoUrls: z.array(z.string()),
  tags: z.optional(z.array(Tag$outboundSchema)),
  status: z.optional(PetStatus$outboundSchema),
});

export function petToJSON(pet: Pet): string {
  return JSON.stringify(Pet$outboundSchema.parse(pet));
}
export function petFromJSON(
  jsonString: string,
): SafeParseResult<Pet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pet' from JSON`,
  );
}
