/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Tag = {
  id?: number | undefined;
  name?: string | undefined;
};

/** @internal */
export const Tag$inboundSchema: z.ZodMiniType<Tag, unknown> = z.object({
  id: types.optional(types.number()),
  name: types.optional(types.string()),
});
/** @internal */
export type Tag$Outbound = {
  id?: number | undefined;
  name?: string | undefined;
};

/** @internal */
export const Tag$outboundSchema: z.ZodMiniType<Tag$Outbound, Tag> = z.object({
  id: z.optional(z.int()),
  name: z.optional(z.string()),
});

export function tagToJSON(tag: Tag): string {
  return JSON.stringify(Tag$outboundSchema.parse(tag));
}
export function tagFromJSON(
  jsonString: string,
): SafeParseResult<Tag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tag' from JSON`,
  );
}
