/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type User = {
  id?: number | undefined;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
  phone?: string | undefined;
  /**
   * User Status
   */
  userStatus?: number | undefined;
};

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.object({
  id: types.optional(types.number()),
  username: types.optional(types.string()),
  firstName: types.optional(types.string()),
  lastName: types.optional(types.string()),
  email: types.optional(types.string()),
  password: types.optional(types.string()),
  phone: types.optional(types.string()),
  userStatus: types.optional(types.number()),
});
/** @internal */
export type User$Outbound = {
  id?: number | undefined;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  password?: string | undefined;
  phone?: string | undefined;
  userStatus?: number | undefined;
};

/** @internal */
export const User$outboundSchema: z.ZodMiniType<User$Outbound, User> = z.object(
  {
    id: z.optional(z.int()),
    username: z.optional(z.string()),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    email: z.optional(z.string()),
    password: z.optional(z.string()),
    phone: z.optional(z.string()),
    userStatus: z.optional(z.int()),
  },
);

export function userToJSON(user: User): string {
  return JSON.stringify(User$outboundSchema.parse(user));
}
export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
