/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteOrderRequest = {
  /**
   * ID of the order that needs to be deleted
   */
  orderId: number;
};

/** @internal */
export type DeleteOrderRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const DeleteOrderRequest$outboundSchema: z.ZodMiniType<
  DeleteOrderRequest$Outbound,
  DeleteOrderRequest
> = z.object({
  orderId: z.int(),
});

export function deleteOrderRequestToJSON(
  deleteOrderRequest: DeleteOrderRequest,
): string {
  return JSON.stringify(
    DeleteOrderRequest$outboundSchema.parse(deleteOrderRequest),
  );
}
