/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Status values that need to be considered for filter
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type Status = ClosedEnum<typeof Status>;

export type FindPetsByStatusRequest = {
  /**
   * Status values that need to be considered for filter
   */
  status?: Status | undefined;
};

/** @internal */
export const Status$outboundSchema: z.ZodMiniEnum<typeof Status> = z.enum(
  Status,
);

/** @internal */
export type FindPetsByStatusRequest$Outbound = {
  status: string;
};

/** @internal */
export const FindPetsByStatusRequest$outboundSchema: z.ZodMiniType<
  FindPetsByStatusRequest$Outbound,
  FindPetsByStatusRequest
> = z.object({
  status: z._default(Status$outboundSchema, "available"),
});

export function findPetsByStatusRequestToJSON(
  findPetsByStatusRequest: FindPetsByStatusRequest,
): string {
  return JSON.stringify(
    FindPetsByStatusRequest$outboundSchema.parse(findPetsByStatusRequest),
  );
}
