/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type FindPetsByTagsRequest = {
  /**
   * Tags to filter by
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export type FindPetsByTagsRequest$Outbound = {
  tags?: Array<string> | undefined;
};

/** @internal */
export const FindPetsByTagsRequest$outboundSchema: z.ZodMiniType<
  FindPetsByTagsRequest$Outbound,
  FindPetsByTagsRequest
> = z.object({
  tags: z.optional(z.array(z.string())),
});

export function findPetsByTagsRequestToJSON(
  findPetsByTagsRequest: FindPetsByTagsRequest,
): string {
  return JSON.stringify(
    FindPetsByTagsRequest$outboundSchema.parse(findPetsByTagsRequest),
  );
}
