/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPetByIdRequest = {
  /**
   * ID of pet to return
   */
  petId: number;
};

/** @internal */
export type GetPetByIdRequest$Outbound = {
  petId: number;
};

/** @internal */
export const GetPetByIdRequest$outboundSchema: z.ZodMiniType<
  GetPetByIdRequest$Outbound,
  GetPetByIdRequest
> = z.object({
  petId: z.int(),
});

export function getPetByIdRequestToJSON(
  getPetByIdRequest: GetPetByIdRequest,
): string {
  return JSON.stringify(
    GetPetByIdRequest$outboundSchema.parse(getPetByIdRequest),
  );
}
