/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetOrderByIdRequest = {
  /**
   * ID of order that needs to be fetched
   */
  orderId: number;
};

/** @internal */
export type GetOrderByIdRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const GetOrderByIdRequest$outboundSchema: z.ZodMiniType<
  GetOrderByIdRequest$Outbound,
  GetOrderByIdRequest
> = z.object({
  orderId: z.int(),
});

export function getOrderByIdRequestToJSON(
  getOrderByIdRequest: GetOrderByIdRequest,
): string {
  return JSON.stringify(
    GetOrderByIdRequest$outboundSchema.parse(getOrderByIdRequest),
  );
}
