/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type LoginUserRequest = {
  /**
   * The user name for login
   */
  username?: string | undefined;
  /**
   * The password for login in clear text
   */
  password?: string | undefined;
};

export type LoginUserResponse = {
  headers: { [k: string]: Array<string> };
  result: string;
};

/** @internal */
export type LoginUserRequest$Outbound = {
  username?: string | undefined;
  password?: string | undefined;
};

/** @internal */
export const LoginUserRequest$outboundSchema: z.ZodMiniType<
  LoginUserRequest$Outbound,
  LoginUserRequest
> = z.object({
  username: z.optional(z.string()),
  password: z.optional(z.string()),
});

export function loginUserRequestToJSON(
  loginUserRequest: LoginUserRequest,
): string {
  return JSON.stringify(
    LoginUserRequest$outboundSchema.parse(loginUserRequest),
  );
}

/** @internal */
export const LoginUserResponse$inboundSchema: z.ZodMiniType<
  LoginUserResponse,
  unknown
> = z.pipe(
  z.object({
    Headers: z._default(z.record(z.string(), z.array(z.string())), {}),
    Result: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  }),
);

export function loginUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoginUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginUserResponse' from JSON`,
  );
}
