/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateUserRequest = {
  /**
   * name that needs to be updated
   */
  username: string;
  /**
   * Update an existent user in the store
   */
  body?: models.User | undefined;
};

/** @internal */
export type UpdateUserRequest$Outbound = {
  username: string;
  body?: models.User$Outbound | undefined;
};

/** @internal */
export const UpdateUserRequest$outboundSchema: z.ZodMiniType<
  UpdateUserRequest$Outbound,
  UpdateUserRequest
> = z.object({
  username: z.string(),
  body: z.optional(models.User$outboundSchema),
});

export function updateUserRequestToJSON(
  updateUserRequest: UpdateUserRequest,
): string {
  return JSON.stringify(
    UpdateUserRequest$outboundSchema.parse(updateUserRequest),
  );
}
