'use client';

import React from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: 'By accessing or using Meridian Node ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to update these terms at any time with notice provided through the platform.',
  },
  {
    title: '2. Description of Service',
    content: 'Meridian Node is an AI-powered land infrastructure intelligence platform that provides site discovery, feasibility analysis, scoring, market intelligence, and reporting tools. The Service includes web-based dashboards, APIs, AI-assisted analysis, and data aggregation from public and licensed sources.',
  },
  {
    title: '3. User Accounts',
    content: 'You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activities under your account. Notify us immediately of any unauthorized use. Accounts are provisioned per organization with role-based access (admin, analyst, viewer).',
  },
  {
    title: '4. Subscription & Billing',
    content: 'Paid plans are billed monthly or annually through Stripe. You authorize us to charge your payment method for recurring fees. Plans auto-renew unless canceled before the period end. Refunds are handled on a case-by-case basis. Usage limits are enforced per plan tier (Explorer, Pro, Enterprise). Exceeding limits will prompt an upgrade.',
  },
  {
    title: '5. Acceptable Use',
    content: 'You may not: (a) reverse engineer or attempt to extract source code; (b) use the Service to violate any law; (c) resell or redistribute data obtained through the Service without authorization; (d) attempt to circumvent usage limits or security measures; (e) use automated tools to scrape or bulk-download data beyond API rate limits.',
  },
  {
    title: '6. Data & Privacy',
    content: 'Your use of the Service is also governed by our Privacy Policy. We aggregate data from public sources (FEMA, EIA, Census, NREL, OSM) and licensed data providers. Site-specific analysis results and reports are owned by you. We may use anonymized, aggregated data to improve the Service.',
  },
  {
    title: '7. API Usage',
    content: 'API access is subject to rate limits based on your plan tier. API keys must be kept confidential. We reserve the right to revoke API access for violations. The API is provided as-is and may be updated with reasonable notice.',
  },
  {
    title: '8. AI-Generated Content',
    content: 'Feasibility analyses, AI chat responses, and portfolio insights are generated by AI models and should be treated as informational, not as professional engineering, legal, or financial advice. Always verify AI-generated recommendations with qualified professionals before making development decisions.',
  },
  {
    title: '9. Limitation of Liability',
    content: 'THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.',
  },
  {
    title: '10. Termination',
    content: 'Either party may terminate at any time. Upon termination, your data will be retained for 30 days before permanent deletion. You may export your data via the API or dashboard before termination takes effect.',
  },
  {
    title: '11. Contact',
    content: 'For questions about these terms, contact us at legal@meridiannode.io or through the Contact page.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      <nav className="border-b border-border bg-bg-secondary/50 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto max-w-4xl px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-accent/10">
              <span className="text-xs font-bold text-accent">M</span>
            </div>
            <span className="font-display text-sm font-bold text-text-primary">Meridian Node</span>
          </Link>
          <Link href="/login" className="text-xs font-medium text-text-secondary hover:text-text-primary transition-colors">Sign In</Link>
        </div>
      </nav>

      <div className="mx-auto max-w-3xl px-6 py-16">
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-display text-3xl font-bold text-text-primary mb-2">Terms of Service</h1>
          <p className="text-sm text-text-muted mb-10">Last updated: March 15, 2026</p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((s, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.03 }}
            >
              <h2 className="font-display text-sm font-bold text-text-primary mb-2">{s.title}</h2>
              <p className="text-xs text-text-secondary leading-relaxed">{s.content}</p>
            </motion.div>
          ))}
        </div>
      </div>

      <footer className="border-t border-border px-6 py-8">
        <div className="mx-auto max-w-4xl flex items-center justify-between">
          <p className="text-xs text-text-muted">&copy; {new Date().getFullYear()} MeridianNode by RKV</p>
          <div className="flex gap-4">
            <Link href="/privacy" className="text-xs text-text-muted hover:text-text-secondary transition-colors">Privacy</Link>
            <Link href="/pricing" className="text-xs text-text-muted hover:text-text-secondary transition-colors">Pricing</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
